services:

  # Serviço para a aplicação Spring Boot
  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    env_file:
      - .env
    environment:
      DATABASE_HOST: database

  # Serviço para o PostgreSQL
  database:
    image: postgres:17.5-alpine3.21
    container_name: database
    restart: always
    ports:
      - "5432:5432"
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
#     volumes:
#       - pg-data:/var/lib/postgresql/data

# volumes:
#   pg-data:
